services:
  - type: web
    name: cigunrehab-bot
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: IO_NET_API_KEY
        sync: false
      - key: ADMIN_TELEGRAM
        value: "@cigunrehab"
      - key: ADMIN_CHAT_ID
        value: "123456789"
      - key: PYTHON_VERSION
        value: "3.11"